# Site settings
title: Living travel blog
email: living-travel@gmail.com
description: All about travelling and living.
baseurl: "/travel-blog"
url: ""
twitter_username: deepak86s
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Deepak sharma" # Set default author name
      categories: "places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
